sync{default.rsyncssh,
  host="gpuseeweb",
  source="./",
  targetdir="/home/ecuser/LaudareBenchmarks",
  excludeFrom=".gitignore",
  exclude = { '.ruff-cache', '.git', 'data/', 'models/', 'fonts/', 'results/', 'logs/', 'analysis/' },
  delete="running",
  delay=0,
  rsync = {
    cvs_exclude = true,
    compress = true,
    _extra = {"--max-size=15mb"},
  }
}

settings{
  nodaemon=true,
  logfile="/tmp/lsync.log"
}
